export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

export const countries: Country[] = [
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹" },
  { code: "BR", name: "Brasil", dialCode: "+55", flag: "🇧🇷" },
  { code: "US", name: "United States", dialCode: "+1", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧" },
  { code: "ES", name: "España", dialCode: "+34", flag: "🇪🇸" },
  { code: "FR", name: "France", dialCode: "+33", flag: "🇫🇷" },
  { code: "DE", name: "Deutschland", dialCode: "+49", flag: "🇩🇪" },
  { code: "IT", name: "Italia", dialCode: "+39", flag: "🇮🇹" },
  { code: "NL", name: "Nederland", dialCode: "+31", flag: "🇳🇱" },
  { code: "BE", name: "Belgique", dialCode: "+32", flag: "🇧🇪" },
  { code: "CH", name: "Schweiz", dialCode: "+41", flag: "🇨🇭" },
  { code: "AT", name: "Österreich", dialCode: "+43", flag: "🇦🇹" },
  { code: "PL", name: "Polska", dialCode: "+48", flag: "🇵🇱" },
  { code: "IE", name: "Ireland", dialCode: "+353", flag: "🇮🇪" },
  { code: "GR", name: "Ελλάδα", dialCode: "+30", flag: "🇬🇷" },
  { code: "SE", name: "Sverige", dialCode: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Norge", dialCode: "+47", flag: "🇳🇴" },
  { code: "DK", name: "Danmark", dialCode: "+45", flag: "🇩🇰" },
  { code: "FI", name: "Suomi", dialCode: "+358", flag: "🇫🇮" },
  { code: "CZ", name: "Česko", dialCode: "+420", flag: "🇨🇿" },
  { code: "RO", name: "România", dialCode: "+40", flag: "🇷🇴" },
  { code: "HU", name: "Magyarország", dialCode: "+36", flag: "🇭🇺" },
  { code: "SK", name: "Slovensko", dialCode: "+421", flag: "🇸🇰" },
  { code: "HR", name: "Hrvatska", dialCode: "+385", flag: "🇭🇷" },
  { code: "SI", name: "Slovenija", dialCode: "+386", flag: "🇸🇮" },
  { code: "BG", name: "България", dialCode: "+359", flag: "🇧🇬" },
  { code: "LT", name: "Lietuva", dialCode: "+370", flag: "🇱🇹" },
  { code: "LV", name: "Latvija", dialCode: "+371", flag: "🇱🇻" },
  { code: "EE", name: "Eesti", dialCode: "+372", flag: "🇪🇪" },
  { code: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺" },
  { code: "MT", name: "Malta", dialCode: "+356", flag: "🇲🇹" },
  { code: "CY", name: "Κύπρος", dialCode: "+357", flag: "🇨🇾" },
  { code: "IS", name: "Ísland", dialCode: "+354", flag: "🇮🇸" },
  { code: "RU", name: "Россия", dialCode: "+7", flag: "🇷🇺" },
  { code: "UA", name: "Україна", dialCode: "+380", flag: "🇺🇦" },
  { code: "TR", name: "Türkiye", dialCode: "+90", flag: "🇹🇷" },
  { code: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦" },
  { code: "MX", name: "México", dialCode: "+52", flag: "🇲🇽" },
  { code: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷" },
  { code: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴" },
  { code: "PE", name: "Perú", dialCode: "+51", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪" },
  { code: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨" },
  { code: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
  { code: "BO", name: "Bolivia", dialCode: "+591", flag: "🇧🇴" },
  { code: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", flag: "🇳🇿" },
  { code: "JP", name: "日本", dialCode: "+81", flag: "🇯🇵" },
  { code: "CN", name: "中国", dialCode: "+86", flag: "🇨🇳" },
  { code: "KR", name: "한국", dialCode: "+82", flag: "🇰🇷" },
  { code: "IN", name: "भारत", dialCode: "+91", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩" },
  { code: "TH", name: "ไทย", dialCode: "+66", flag: "🇹🇭" },
  { code: "VN", name: "Việt Nam", dialCode: "+84", flag: "🇻🇳" },
  { code: "MY", name: "Malaysia", dialCode: "+60", flag: "🇲🇾" },
  { code: "SG", name: "Singapore", dialCode: "+65", flag: "🇸🇬" },
  { code: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭" },
  { code: "HK", name: "香港", dialCode: "+852", flag: "🇭🇰" },
  { code: "TW", name: "台灣", dialCode: "+886", flag: "🇹🇼" },
  { code: "AE", name: "الإمارات", dialCode: "+971", flag: "🇦🇪" },
  { code: "SA", name: "السعودية", dialCode: "+966", flag: "🇸🇦" },
  { code: "IL", name: "ישראל", dialCode: "+972", flag: "🇮🇱" },
  { code: "EG", name: "مصر", dialCode: "+20", flag: "🇪🇬" },
  { code: "MA", name: "المغرب", dialCode: "+212", flag: "🇲🇦" },
  { code: "ZA", name: "South Africa", dialCode: "+27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴" },
  { code: "MZ", name: "Moçambique", dialCode: "+258", flag: "🇲🇿" },
  { code: "CV", name: "Cabo Verde", dialCode: "+238", flag: "🇨🇻" },
];

export const defaultCountry = countries[0]; // Portugal
